basic:
   url: ssl://emqx.rexense.com:8883
   username: rexense
   password: rexense
   broker: https://www.kc.com:443
functionality:
  gateway:
    gw_message_up:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/message/up
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${gwVC}
          timestamp: ${timestamp}
          sequence: ${IOTA}
          data:
            - productKey: ${devPK}
              deviceName: ${devDN}
    gw_command:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          id: ${IOTA}
          params:
            - productKey: ${devPK}
              deviceName: ${devDN}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          id: ${ID}
          code: ${CODE}
          data:
            - productKey: ${devPK}
              deviceName: ${devDN}
      match: ["id"]
      success:
        CODE: 0
    gw_ota:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/ota/ack
        payload:
          id: ${IOTA}
          params:
            - productKey: ${devPK}
              deviceName: ${devDN}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/ota/ack
        payload:
          id: ${ID}
          code: ${CODE}
          data:
            - productKey: ${devPK}
              deviceName: ${devDN}
      match: ["id"]
      success:
        CODE: 0
    topo_join:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/message/up
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${gwVC}
          timestamp: ${timestamp}
          sequence: ${IOTA}
          data:
            - model: ${gwMD}
              parentDeviceId: ${parentDeviceId}
              name: ${name}
              code: "${code}"
    topo_leave:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/message/up
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${gwVC}
          timestamp: ${timestamp}
          sequence: ${IOTA}
          data:
            - model: ${gwMD}
              parentDeviceId: ${parentDeviceId}
              name: ${name}
              code: "${code}"
    topo_delete:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/topo/change
        payload:
          id: ${ID}
          status: 1
          params:
            - productKey: ${devPK}
              deviceName: ${devDN}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/topo/change_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    gw_login:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/login
        payload:
          id: ${IOTA}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/login_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    gw_logout:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/logout
        payload:
          id: ${IOTA}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/logout_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    create_zigbee_network:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/create_zigbee_network
        payload: 
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/create_zigbee_network_reply
        payload:
          id: ${ID}
          code: ${CODE}
    leave_zigbee_network:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/leave_zigbee_network
        payload:
          id: ${ID}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/leave_zigbee_network_reply
        payload:
          id: ${ID}
          code: ${CODE}
    start_permit_join:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value:
                join_second: ${join_second}
                join_type: ${join_type}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value: ${value}
    stop_permit_join:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value: ${value}
    create_scene:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_create_update
        payload:
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_create_update_reply
        payload:
          id: ${ID}
          code: ${CODE}
    delete_scene:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_delete
        payload:
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_delete_reply
        payload:
          id: ${ID}
          code: ${CODE}
    trigger_scene:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_trigger
        payload:
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_trigger_reply
        payload:
          id: ${ID}
          code: ${CODE}
    enable_scene:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_enable
        payload:
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_enable_reply
        payload:
          id: ${ID}
          code: ${CODE}
    disable_scene:
      request:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_disable
        payload:
          id: ${ID}
          params:
            - key: ${param_name}
              value: ${param_value}
      response:
        topic: /sys/${gwPK}/${gwDN}/thing/service/scene_disable_reply
        payload:
          id: ${ID}
          code: ${CODE}
    report_version:
      request:
        topic: /sys/${gwPK}/${gwDN}/ota/device/inform
        payload:
          id: ${IOTA}
          params:
            - module: ${module_name}
              version: ${version_str}
      response:
        topic: /sys/${gwPK}/${gwDN}/ota/device/inform_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    ota_request:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              version: ${version}
              type: ${type}
              code: ${code}
              value: ${value}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value: ${value}
    ota_progress:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/message/up
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${gwDN}
              code: ${code}
              value: ${value}
  device:
    dev_login:
      request:
        topic: /sys/${gwPK}/${gwDN}/sub/login
        payload:
          id: ${IOTA}
          params:
            - productKey: ${devPK}
              deviceName: ${devDN}
      response:
        topic: /sys/${gwPK}/${gwDN}/sub/login_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    dev_logout:
      request:
        topic: /sys/${gwPK}/${gwDN}/sub/logout
        payload:
          id: ${IOTA}
          params:
            - productKey: ${devPK}
              deviceName: ${devDN}
      response:
        topic: /sys/${gwPK}/${gwDN}/sub/logout_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    dev_property_post:
      request:
        topic: /sys/${devPK}/${devDN}/thing/event/property/post
        payload:
          id: ${IOTA}
          params:
            - name: ${property_name}
              value: ${property_value}
              time: ${TIMESTAMP}
      response:
        topic: /sys/${devPK}/${devDN}/thing/event/property/post_reply
        payload:
          id: ${ID}
          code: ${CODE}
      match: ["id"]
      success:
        CODE: 0
    dev_property_set:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              version: ${version}
              type: ${type}
              code: ${code}
              value: ${value}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value: ${value}
    dev_event_post:
      - request:
          topic: /sys/${devPK}/${devDN}/thing/event/${event_name}/post
          payload:
            id: ${IOTA}
            params: ${params}
          time: ${TIMESTAMP}
        response:
          topic: /sys/${devPK}/${devDN}/thing/event/${event_name}/post_reply
          payload:
            id: ${ID}
            code: ${CODE}
        match: ["id"]
        success:
          CODE: 0
    dev_service_call:
      - request:
          topic: /sys/${devPK}/${devDN}/thing/service/${service_name}
          payload:
            id: ${ID}
            params:
              - key: ${param_name}
                value: ${param_value}
        response:
          topic: /sys/${devPK}/${devDN}/thing/service/${service_name}_reply
          payload:
            id: ${ID}
            code: ${CODE}
        match: ["id"]
        success:
          CODE: 0
    dev_set_alias:
      request:
        topic: /sys/${devPK}/${devDN}/thing/service/alias/set
        payload:
          id: ${ID}
          alias: ${alias}
      response:
        topic: /sys/${devPK}/${devDN}/thing/service/alias/set_reply
        payload:
          id: ${ID}
          code: ${CODE}
    dev_ota_request:
      request:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/down
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              version: ${version}
              type: ${type}
              code: ${code}
              value: ${value}
      response:
        topic: ${gwVC}/${gwMD}/${gwDN}/command/ack
        payload:
          version: ${version}
          flowDirection: ${flowDirection}
          controlType: ${controlType}
          messageType: ${messageType}
          vendor: ${vendor}
          timestamp: ${timestamp}
          sequence: ${sequence}
          data:
            - model: ${model}
              parentDeviceId: ${parentDeviceId}
              deviceId: ${deviceId}
              code: ${code}
              value: ${value}
    dev_ota_progress:
      request:
        topic: /sys/${devPK}/${devDN}/ota/device/progress
        payload:
          id: ${ID}
          step: ${OTA_STEP}
          desc: ${OTA_DESC}
